### ISSUE TITLE
Integrate button management portal into dingdongdash.com website and make unique

### ISSUE THREAD

**Issue by TroyScarbrough** [aphelionz/dingdongdash#13]
1. We need to integrate the client portal of https://app.dingdongdash.net into the account portal of the sales website - https://dingdongdash.net/account.

- Include: when a person logs in to their account on the sales website they can see their orders and see/manage their button actions etc.  This will allow us to have a one stop shop and allow us to continuously upsell.  (at some point they will be able to manage their account through an app on their phone)

- Make each account unique = when i logged into the client portal to "manage my buttons" I could see the perkins information as an option.  This needs to be clean for every new customer.

**Comment by aphelionz** [comment]
Ok, that sounds good. This is stuff we need to plan out one of these nights

**Comment by aphelionz** [comment]
@oliverbhull Here's instructions on how to satisfy this ticket.

Setup
====

1. Run `git checkout upstream 13-shopify-integration` to get the code on this branch.
2. Delete all your existing user groups ("CoreUser", etc) using the admin panel
3. Run `python manage.py migrate` to get the latest group configuration

Development
=========

I wrote an automated test that you will need to pass. Run `python manage.py test api` and observe that it fails. Your job is to complete the function [here](https://github.com/aphelionz/dingdongdash/blob/13-shopify-integration/api/views.py#L42) to make the test pass. It will be looking for 5 criteria:

1. A new user is created
2. The user is added to the "RequiresPasswordChange" group.
3. A new button action is created that texts the customer's phone.
4. A new button is created with the name 'UNASSIGNED". You will need to pass the timestamp in as the button serial_number since serial_number needs to be unique.
5. The API returns a 201 CREATED status code on success.

Refer to the test itself, the code in api/views.py and core/functions.py, and the Django docs on how to do all of this.

Let me know if you have any questions! Thank you!
