### ISSUE TITLE
Adding a New User from a New Action & Email Addresses

### ISSUE THREAD

**Issue by TroyScarbrough** [aphelionz/dingdongdash#38]
1.) If you start by trying to add an Action, and then realize you need to add a new user (which brings you to "add a phone"), if you click to add a new user again on the "add phone" page popup (which should include add email option -see #2 below), when you enter the new user information on the second popup screen and it automatically takes you back to the "add a phone" popup, that new user information you just entered is not available in the dropdown even if you refresh.

2.) Where we enter the phone number we need to be able to enter an email address for the email action also.

**Comment by aphelionz** [comment]
I think storing the contact information with the user object is going to be the key here. right now it's stored seperately as a "Phone" but it really needs to be the phone number associated with the "User." That will handle #2

As for #1, you don't see them because they're not a part of the same organization as you are. so I will add a script that adds them to the organization of the user that created them. That will fix #1
